with open('Pr_Liste_input.txt', 'r') as f:
    x=list(eval(f.readline()))
print("Lista initiala este:", x)
a=sorted(x)
print("Lista sortata in ordine crescatoare este:", a)
b=sorted(x, reverse=True)
print("Lista sortata in ordine descrescatoare:", b)
print("Lungimea listei initiale este:", len(x))
print("Elementul MAX este:", max(x))
print("Elementul MIN este:", min(x))
x.append(111)
print("Lista nou-formata cu elementul 111 este:", x)
x.remove(111)
x.insert(2,222)
print("Lista nou-formata cu elementul 222:", x)